public class Main {
    public static void main(String[] args) {
        System.out.println("Hello world!");
        var dog = 8.0;
        System.out.println(dog);
        var cat = 3.6;
        System.out.println(cat);
        var paper = 764789;
        System.out.println(paper);
        dog = dog + 4;
        System.out.println(dog);
        cat = cat + 4;
        System.out.println(cat);
        paper = paper + 4;
        System.out.println(paper);
        dog = dog - 3.5;
        System.out.println(dog);
        cat = cat - 1.6;
        System.out.println(cat);
        paper = paper - 7639;
        System.out.println(paper);
        var friend = 19;
        System.out.println(friend);
        friend = friend * 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        var boxer1 = 78.2;
        System.out.println(boxer1);
        var boxer2 = 82.7;
        System.out.println(boxer2);
        var ufc = boxer1 + boxer2;
        System.out.println("Общий вес " + ufc + " кг! ");
        var ves = boxer2 - boxer1;
        System.out.println(" разница в " + ves +" кг! ");
        var overload = (boxer1 + boxer2) % ves;
        System.out.println(" разница на "+ overload + "кг!");
        var time = 640;
        System.out.println(time);
        var man = 8;
        System.out.println(man);
        var sotrudnik = time / man;
        System.out.println("всего сотрудников " + sotrudnik);
        var sotrudnik2 = 94;
        System.out.println(sotrudnik2);
        var sotrudnik3 = sotrudnik + sotrudnik2;
        System.out.println(sotrudnik3);
        var time2 = time / sotrudnik3;
        System.out.println(time2);
        System.out.println("если в компании работает " + sotrudnik2 + " человек,то всего " + time2 + " часов работы может быть поделено между сотрудниками");
    }
}